name: Python CI

on:
  push:
    branches:
      - master

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install Dependencies
        run: |
          pip install flask
          pip install pytest

      - name: Run Tests
        run: pytest

      - name: Build Docker Image
        run: docker build -t simple-cicd-app .